# Generated by Django 4.2.1 on 2023-05-24 03:23
import os
import re
from django.db import migrations
from django.conf import settings

""" 
    we assume that all posts are formatted in the same way ie:
    ===
    Title: some title
    Author: some author
    Slug: filename-minus-.md
    ===
    markdown content....
"""
def create_posts_from_files(apps, schema_editor):
    # the directory should really be an environment variable
    Post = apps.get_model('posts', 'Post')
    notags_re = re.compile('<.*?>')
    for filename in os.listdir(os.path.join(settings.BASE_DIR, 'posts/posts-seed-files')):
        if filename.endswith('.md'):
            filepath = os.path.join(settings.BASE_DIR, 'posts/posts-seed-files', filename)
            with open(filepath) as f:
                slug = filename[:-3]
                lines = f.readlines()
                title = lines[1].replace('Title: ', '', 1)
                content = "\n".join(lines[5:])
                content_cleaned = re.sub(notags_re, '', content)
                post = Post(content=content_cleaned, slug=slug, title=title)
                post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_posts_from_files)
    ]
